apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /k8s_test2/favicon.ico
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: git-volume
            mountPath: /usr/share/nginx/html
      volumes:
      - name: git-volume
        gitRepo:
          repository: "https://github.com/sofinan/k8s_test2.git"
---

apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80